### ISSUE TITLE
App is broken in prod! - point to DEV/PRD database dynamically

### ISSUE THREAD

**Issue by justinliu6165** [justinliu6165/kodflix#33]
https://github.com/rmallols/kodflix/issues/30

**Comment by justinliu6165** [comment]
2 issues:
1. File name change changes on github but not on heroku
2. dotenv does not work on heroku; added an or statement so production able to find process.env.DB_URL_PRD

**Comment by rmallols** [comment]
Hi Justin,

1. [Did you try this?](https://help.github.com/articles/renaming-a-file-using-the-command-line/)
2. Didn't get that. Technically speaking, dotenv can perfectly work on Heroku or any other cloud platform. In that respect, you won't obviously have access to `.env`, as that file is ignored. But, still, if the env variable exists (e.g. `DB_URL_PRD`), you'll be able to access it. [Just make sure the required variables exists on Heroku.](https://devcenter.heroku.com/articles/config-vars)

**Comment by justinliu6165** [comment]
oh yea it works now. The comments were more of a reminder for later haha but thanks for the reply. 
The 2nd issue was that the databaseUrl variable was not finding process.env.NODE_ENV(which = PRD) even after i had entered 'heroku config: set DB_URL_PRD = ...' so i added an OR condition: 

const databaseUrl = process.env[`DB_URL_${process.env.NODE_ENV}`] || process.env.DB_URL_PRD;

not sure if this is the right way to do it, but it seems to work

**Comment by rmallols** [comment]
Ah right! Re. the database issue, I may know what the issue is. I get the feeling Heroku is ignoring the `NODE_ENV=PRD` variable, but I think we can fix it.

Could you please add a new env variable on Heroku, using CLI, to set `NODE_ENV=PRD` (and remove it from `package.json`), That should work, and would avoid defaulting to `PRD` as you are doing at the moment, which is risky at some extend.

**Comment by justinliu6165** [comment]
okay, i've just implemented the changes and it seems to all work now too. Thanks a lot Ricardo!

**Comment by rmallols** [comment]
No probs mate! 👍 🥇
